services:
  db-tests:
    container_name: db-tests
    build:
      context: ../
      dockerfile: ./api/repository-jdbi/docker/Dockerfile
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5432:5432"