services:
  db-tests:
    container_name: db-tests
    build:
      context: ./repository-jdbi
      dockerfile: ./docker/Dockerfile
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=changeit
      - POSTGRES_DB=db
    ports:
      - "5432:5432"